services:
  ueba-eng:
    build: .
    image: masa555/ueba:ueba-0.8.0
    container_name: ueba_eng
    environment:
      - DATA_KEEP_DAYS=${DATA_KEEP_DAYS}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTH=${SMTP_AUTH}
      - SMTP_AUTH_USER=${SMTP_AUTH_USER}
      - SMTP_AUTH_PASS=${SMTP_AUTH_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_STARTTLS=${SMTP_STARTTLS}
      - SMTP_TO=${SMTP_TO}
      - SMTP_SUBJECT="${SMTP_SUBJECT}"
    # 外部に公開するポート => "ホスト側:コンテナ側"
    ports:
      - "10022:22"     # SSH (ホストの10022 => コンテナの22)
      - "10080:80"     # HTTP (ホストの10080 => コンテナの80)
      - "10443:443"    # HTTP (ホストの10443 => コンテナの443)
    volumes:
      - ./logs/httpd:/var/log/httpd
      - ./logs/ueba:/var/log/ueba  # 任意: ログディレクトリをホストにマウントしたい場合など
      - ./reports:/var/www/html/reports
      - ./uploads:/home/ueba/uploads
      - ssh_key:/home/ueba/.ssh
      - sshd_key:/etc/ssh
      - pki_keys:/etc/pki
    tty: true
    stdin_open: true

volumes:
  ssh_key:
  sshd_key:
  pki_keys:
